#!/usr/bin/env python3
"""
file_processor.py - JSON File Processing Practice

Learning to parse JSON files and generate documentation.
Exercise from DataCamp "Working with Files in Python" course.
"""

import sys
from pathlib import Path
from json_parser import JsonParser
from diagram_generator import DiagramBuilder


def process_json_file(filepath: str, output_format: str = "markdown") -> str:
    """Process a JSON file and generate documentation"""
    # Parse the JSON file
    parser = JsonParser(filepath)
    data = parser.parse()
    
    # Generate appropriate output
    if output_format == "diagram":
        return generate_flow_diagram(data)
    elif output_format == "summary":
        return generate_summary(data)
    else:
        return generate_documentation(data)


def generate_flow_diagram(data: dict) -> str:
    """Generate a flow diagram from JSON data"""
    builder = DiagramBuilder()
    builder.title(f"Workflow: {data['name']}")
    
    # Create simple node IDs (node0, node1, etc.)
    component_to_node = {}
    for i, (comp_id, label) in enumerate(data['components'].items()):
        node_id = f"node{i}"
        component_to_node[comp_id] = node_id
        builder.node(node_id, label)
    
    # Add connections
    for src_id, dst_id, link_id in data['connections']:
        src_node = component_to_node[src_id]
        dst_node = component_to_node[dst_id]
        builder.edge(src_node, dst_node, link_id)
    
    return builder.build()


def generate_summary(data: dict) -> str:
    """Generate a summary of the JSON data"""
    stats = data['stats']
    return f"""# File Processing Summary

**Workflow**: {data['name']}
**Components**: {stats['component_count']}
**Connections**: {stats['connection_count']}
**Complexity**: {stats['complexity']}

## Components
{chr(10).join(f"- {label}" for label in data['components'].values())}
"""


def generate_documentation(data: dict) -> str:
    """Generate complete documentation from JSON data"""
    stats = data['stats']
    
    # Build the documentation
    doc = f"""# {data['name']}

## Overview
- **Components**: {stats['component_count']}
- **Connections**: {stats['connection_count']}
- **Complexity**: {stats['complexity']}

## Components

"""

    for i, label in enumerate(data['components'].values(), 1):
        doc += f"{i}. **{label}**\n"

    doc += f"""

## Workflow Diagram

{generate_flow_diagram(data)}

## Connection Details

"""

    # Add connection table if there are connections
    if data['connections']:
        doc += "| From | To | Link ID |\n"
        doc += "|------|----|---------|\n"
        
        for src_id, dst_id, link_id in data['connections']:
            src_label = data['components'][src_id]
            dst_label = data['components'][dst_id]
            doc += f"| {src_label} | {dst_label} | `{link_id}` |\n"
    else:
        doc += "*This workflow has no internal connections.*"
    
    doc += "\n\n---\n*Generated by file processor (DataCamp practice)*"
    
    return doc


def main():
    """Main function for file processing practice"""
    if len(sys.argv) < 2:
        print("Usage: file_processor.py <data_file.json> [output.md]")
        print("\nOptions:")
        print("  file_processor.py data.json              # Print to stdout")
        print("  file_processor.py data.json doc.md       # Save to file")
        print("  file_processor.py data.json --summary    # Show summary only")
        print("  file_processor.py data.json --diagram    # Diagram only")
        return 1
    
    input_file = sys.argv[1]
    
    try:
        # Process the file
        print(f"📊 Processing {input_file}...", file=sys.stderr)
        
        # Check for special flags
        if len(sys.argv) > 2:
            if sys.argv[2] == "--summary":
                data = JsonParser(input_file).parse()
                print(f"\n📈 File Processing Summary:")
                print(f"Name: {data['name']}")
                print(f"Components: {data['stats']['component_count']}")
                print(f"Connections: {data['stats']['connection_count']}")
                print(f"Complexity: {data['stats']['complexity']}")
                return 0
            
            elif sys.argv[2] == "--diagram":
                data = JsonParser(input_file).parse()
                print("\n🌊 Flow Diagram:")
                print(generate_flow_diagram(data))
                return 0
        
        # Generate documentation
        print("📝 Generating documentation...", file=sys.stderr)
        documentation = process_json_file(input_file)
        
        # Output
        if len(sys.argv) > 2 and not sys.argv[2].startswith('--'):
            # Save to file
            output_file = sys.argv[2]
            Path(output_file).write_text(documentation, encoding='utf-8')
            print(f"✅ Documentation saved to {output_file}", file=sys.stderr)
        else:
            # Print to stdout
            print("\n" + "="*60)
            print(documentation)
            print("="*60)
        
        return 0
        
    except Exception as e:
        print(f"❌ Error: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
