import sys
import json
from pathlib import Path
from json_parser import JsonParser
from diagram_builder import build_pipeline_diagram as data_processing_workflow


def load_first_pipeline(filepath: str) -> dict:
    """Load the export file and return the first pipeline entry."""
    with open(filepath, "r", encoding="utf-8") as f:
        raw_data = json.load(f)

    if "entries" not in raw_data or not raw_data["entries"]:
        raise ValueError("No pipeline entries found in export file")

    return raw_data["entries"][0]


def process_json_file(filepath: str, output_format: str = "markdown") -> str:
    """Process a SnapLogic export file and generate documentation."""
    first_pipeline = load_first_pipeline(filepath)
    parser = JsonParser(first_pipeline)
    data = parser.parse()

    if output_format == "diagram":
        return data_processing_workflow(
            data["name"],
            data["components"],
            data["connections"],
        )
    elif output_format == "summary":
        return generate_summary(data)
    else:
        return generate_documentation(data)


def generate_summary(data: dict) -> str:
    """Generate a summary of the parsed pipeline data."""
    stats = data["stats"]
    return f"""# File Processing Summary

**Workflow**: {data['name']}
**Components**: {stats['component_count']}
**Connections**: {stats['connection_count']}
**Complexity**: {stats['complexity']}

## Components
{chr(10).join(f"- {label}" for label in data['components'].values())}
"""


def generate_documentation(data: dict) -> str:
    """Generate complete documentation from parsed pipeline data."""
    stats = data["stats"]

    diagram = data_processing_workflow(
        data["name"],
        data["components"],
        data["connections"],
    )

    doc = f"""# {data['name']}

## Overview
- **Components**: {stats['component_count']}
- **Connections**: {stats['connection_count']}
- **Complexity**: {stats['complexity']}

## Components

"""

    for i, label in enumerate(data["components"].values(), 1):
        doc += f"{i}. **{label}**\n"

    doc += f"""

## Workflow Diagram

{diagram}

## Connection Details

"""

    if data["connections"]:
        doc += "| From | To | Link ID |\n"
        doc += "|------|----|---------|\n"

        for src_id, dst_id, link_id in data["connections"]:
            src_label = data["components"][src_id]
            dst_label = data["components"][dst_id]
            doc += f"| {src_label} | {dst_label} | `{link_id}` |\n"
    else:
        doc += "*This workflow has no internal connections.*"

    doc += "\n\n---\n*Generated by file processor (Goldilocks)*"

    return doc


def main():
    """Main function for processing a SnapLogic export file."""
    if len(sys.argv) < 2:
        print("Usage: python src/pipeline_processor.py <data_file.json> [output.md]")
        print("\nOptions:")
        print("  python src/pipeline_processor.py export.json              # Print documentation")
        print("  python src/pipeline_processor.py export.json doc.md       # Save documentation")
        print("  python src/pipeline_processor.py export.json --summary    # Show summary only")
        print("  python src/pipeline_processor.py export.json --diagram    # Diagram only")
        return 1

    input_file = sys.argv[1]

    try:
        print(f"📊 Processing {input_file}...", file=sys.stderr)

        first_pipeline = load_first_pipeline(input_file)
        data = JsonParser(first_pipeline).parse()

        if len(sys.argv) > 2:
            if sys.argv[2] == "--summary":
                print("\n📈 File Processing Summary:")
                print(f"Name: {data['name']}")
                print(f"Components: {data['stats']['component_count']}")
                print(f"Connections: {data['stats']['connection_count']}")
                print(f"Complexity: {data['stats']['complexity']}")
                return 0

            elif sys.argv[2] == "--diagram":
                print("\n🌊 Flow Diagram:")
                print(
                    data_processing_workflow(
                        data["name"],
                        data["components"],
                        data["connections"],
                    )
                )
                return 0

        print("📝 Generating documentation...", file=sys.stderr)
        documentation = generate_documentation(data)

        if len(sys.argv) > 2 and not sys.argv[2].startswith("--"):
            output_file = sys.argv[2]
            Path(output_file).write_text(documentation, encoding="utf-8")
            print(f"✅ Documentation saved to {output_file}", file=sys.stderr)
        else:
            print("\n" + "=" * 60)
            print(documentation)
            print("=" * 60)

        return 0

    except Exception as e:
        print(f"❌ Error: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())